# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Storage service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LearnConcept = channel.unary_unary(
                '/sutra.storage.StorageService/LearnConcept',
                request_serializer=storage__pb2.LearnConceptRequest.SerializeToString,
                response_deserializer=storage__pb2.LearnConceptResponse.FromString,
                _registered_method=True)
        self.QueryConcept = channel.unary_unary(
                '/sutra.storage.StorageService/QueryConcept',
                request_serializer=storage__pb2.QueryConceptRequest.SerializeToString,
                response_deserializer=storage__pb2.QueryConceptResponse.FromString,
                _registered_method=True)
        self.LearnAssociation = channel.unary_unary(
                '/sutra.storage.StorageService/LearnAssociation',
                request_serializer=storage__pb2.LearnAssociationRequest.SerializeToString,
                response_deserializer=storage__pb2.LearnAssociationResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/sutra.storage.StorageService/GetNeighbors',
                request_serializer=storage__pb2.GetNeighborsRequest.SerializeToString,
                response_deserializer=storage__pb2.GetNeighborsResponse.FromString,
                _registered_method=True)
        self.FindPath = channel.unary_unary(
                '/sutra.storage.StorageService/FindPath',
                request_serializer=storage__pb2.FindPathRequest.SerializeToString,
                response_deserializer=storage__pb2.FindPathResponse.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_unary(
                '/sutra.storage.StorageService/VectorSearch',
                request_serializer=storage__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=storage__pb2.VectorSearchResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/sutra.storage.StorageService/GetStats',
                request_serializer=storage__pb2.StatsRequest.SerializeToString,
                response_deserializer=storage__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/sutra.storage.StorageService/Flush',
                request_serializer=storage__pb2.FlushRequest.SerializeToString,
                response_deserializer=storage__pb2.FlushResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sutra.storage.StorageService/HealthCheck',
                request_serializer=storage__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=storage__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Storage service definition
    """

    def LearnConcept(self, request, context):
        """Concept operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryConcept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LearnAssociation(self, request, context):
        """Association operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPath(self, request, context):
        """Path finding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """Vector operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LearnConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.LearnConcept,
                    request_deserializer=storage__pb2.LearnConceptRequest.FromString,
                    response_serializer=storage__pb2.LearnConceptResponse.SerializeToString,
            ),
            'QueryConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryConcept,
                    request_deserializer=storage__pb2.QueryConceptRequest.FromString,
                    response_serializer=storage__pb2.QueryConceptResponse.SerializeToString,
            ),
            'LearnAssociation': grpc.unary_unary_rpc_method_handler(
                    servicer.LearnAssociation,
                    request_deserializer=storage__pb2.LearnAssociationRequest.FromString,
                    response_serializer=storage__pb2.LearnAssociationResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=storage__pb2.GetNeighborsRequest.FromString,
                    response_serializer=storage__pb2.GetNeighborsResponse.SerializeToString,
            ),
            'FindPath': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPath,
                    request_deserializer=storage__pb2.FindPathRequest.FromString,
                    response_serializer=storage__pb2.FindPathResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=storage__pb2.VectorSearchRequest.FromString,
                    response_serializer=storage__pb2.VectorSearchResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=storage__pb2.StatsRequest.FromString,
                    response_serializer=storage__pb2.StatsResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=storage__pb2.FlushRequest.FromString,
                    response_serializer=storage__pb2.FlushResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=storage__pb2.HealthCheckRequest.FromString,
                    response_serializer=storage__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sutra.storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sutra.storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Storage service definition
    """

    @staticmethod
    def LearnConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/LearnConcept',
            storage__pb2.LearnConceptRequest.SerializeToString,
            storage__pb2.LearnConceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/QueryConcept',
            storage__pb2.QueryConceptRequest.SerializeToString,
            storage__pb2.QueryConceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LearnAssociation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/LearnAssociation',
            storage__pb2.LearnAssociationRequest.SerializeToString,
            storage__pb2.LearnAssociationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/GetNeighbors',
            storage__pb2.GetNeighborsRequest.SerializeToString,
            storage__pb2.GetNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/FindPath',
            storage__pb2.FindPathRequest.SerializeToString,
            storage__pb2.FindPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/VectorSearch',
            storage__pb2.VectorSearchRequest.SerializeToString,
            storage__pb2.VectorSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/GetStats',
            storage__pb2.StatsRequest.SerializeToString,
            storage__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/Flush',
            storage__pb2.FlushRequest.SerializeToString,
            storage__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutra.storage.StorageService/HealthCheck',
            storage__pb2.HealthCheckRequest.SerializeToString,
            storage__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
